openapi: 3.0.0
info:
  title: Product Service API
  version: 1.0.0

servers:
  - url: 'https://akj8ohr428.execute-api.eu-north-1.amazonaws.com/dev'

paths:
  /products:
    get:
      summary: Get a list of Products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Get a product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the Product.
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number
    Error:
      type: object
      properties:
        message:
          type: string