
service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-north-1
  httpApi:
    cors: true

  iamRoleStatements:
    - Effect: Allow
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::import-service-bucket-lab"
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::import-service-bucket-lab/*"
    - Effect: Allow
      Action: sqs:*
      Resource: arn:aws:sqs:eu-north-1:688798769247:catalogItemsQueue

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
     - httpApi:
        path: /import
        method: get
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-service-bucket-lab
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
    environment:
      SQS_URL: https://sqs.eu-north-1.amazonaws.com/688798769247/catalogItemsQueue

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
